# Generated by Django 5.2.9 on 2026-02-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytask',
            name='task',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studytask',
            name='title',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='daily_hours',
            field=models.PositiveIntegerField(),
        ),
    ]
