# Generated by Django 5.2.9 on 2026-02-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplan', '0002_remove_studytask_task_studyplan_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studytask',
            old_name='title',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='daily_hours',
            field=models.IntegerField(),
        ),
    ]
