# Generated by Django 6.0 on 2026-01-04 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerecord',
            name='access_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='issue_type',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PHYSICAL', 'Physical')], default='PHYSICAL', max_length=10),
        ),
    ]
