# Generated by Django 6.0 on 2026-01-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
