# Generated by Django 5.2.9 on 2026-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_issuedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='50-60 word book description', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, help_text='Total number of pages', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 5.0', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True),
        ),
    ]
