# Generated by Django 5.2.9 on 2026-02-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=4.5, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.TextField(blank=True, default='', help_text='Comma-separated tags'),
        ),
    ]
