# Generated by Django 5.2.9 on 2025-12-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('total_issues', models.IntegerField(default=0)),
                ('total_returns', models.IntegerField(default=0)),
                ('most_read_category', models.CharField(blank=True, max_length=200, null=True)),
                ('peak_hour', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
