# Generated by Django 5.2.9 on 2026-02-07 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_analytics', '0002_book_userbookactivity_usermonthlyanalytics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('book_view', 'Book View'), ('book_search', 'Book Search'), ('book_issue', 'Book Issue'), ('book_return', 'Book Return'), ('study_plan_create', 'Study Plan Created'), ('study_plan_update', 'Study Plan Updated'), ('task_complete', 'Task Completed'), ('attendance_mark', 'Attendance Marked'), ('login', 'Login'), ('logout', 'Logout')], max_length=50)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='library_ana_user_id_d3040f_idx'), models.Index(fields=['event_type', '-timestamp'], name='library_ana_event_t_f41677_idx')],
            },
        ),
    ]
